# Generated by Django 6.1 on 2026-09-13 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('year_start', models.CharField(max_length=15)),
                ('year_end', models.CharField(max_length=15)),
            ],
        ),
    ]
