# Generated by Django 6.1 on 2026-09-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('formal', 'Formal'), ('informal', 'Informal')], default='formal', max_length=31),
        ),
    ]
